"""
02_ai_detection.py
==================
Classifies whether a post's image is AI-generated using a multi-signal approach:

Signal 1 — Keyword heuristics:
  Posts explicitly tagged with #GrokAI, "made with Grok", "ai generated", etc.
  are labeled as AI-generated with high confidence.

Signal 2 — CLIP-based zero-shot classifier:
  Uses OpenAI's CLIP model to compare image embeddings against text prompts
  "a real photograph" vs "an AI-generated image". This is a lightweight
  approach that runs on CPU and requires no labeled training data.

Signal 3 (Optional) — Grok watermark detection:
  Grok images currently embed a metadata tag ("source: Grok") in EXIF/XMP.
  We attempt to read this via the Pillow library.

Note from Prof: "Are Grok images watermarked?"
  → Yes, as of early 2025 Grok embeds "Made with Grok" text overlays on some
    outputs but NOT reliably on all. Therefore we use Signal 1 + 2 as primary.

Usage:
  python 02_ai_detection.py --input data/synthetic/synthetic_posts.csv
  python 02_ai_detection.py --input data/processed/treatment_posts.csv
"""

import argparse
import re
import requests
import pandas as pd
import numpy as np
from pathlib import Path
from io import BytesIO

PROC_DIR = Path("data/processed")
PROC_DIR.mkdir(parents=True, exist_ok=True)

# ── Signal 1: Keyword Heuristics ─────────────────────────────────────────────
AI_KEYWORDS = [
    r"\bgrok\b", r"\bai.?generated\b", r"\bai.?gen\b", r"\bsyntheticmedia\b",
    r"\bmade.?with.?grok\b", r"\bgrokimage\b", r"\bgrok.?ai\b",
    r"\bdiffusion\b", r"\bmidjourney\b", r"\bstable.?diffusion\b",
    r"\bdall.?e\b", r"\bflux\b", r"\baiart\b",
    # Explicit markers
    r"made by ai", r"generated by ai", r"#grok", r"#aiart", r"#aiimage"
]

COMPILED_PATTERNS = [re.compile(p, re.IGNORECASE) for p in AI_KEYWORDS]


def keyword_classify(text: str) -> tuple[bool | None, float]:
    """
    Returns (is_ai, confidence) based on keyword matching.
    None if no signal found.
    """
    if not isinstance(text, str):
        return None, 0.0

    matches = sum(1 for pat in COMPILED_PATTERNS if pat.search(text))
    if matches >= 2:
        return True, 0.95
    elif matches == 1:
        return True, 0.75
    return None, 0.0


# ── Signal 2: CLIP Zero-Shot Classifier ──────────────────────────────────────
# Only loaded if images are available and torch/transformers are installed
def load_clip_model():
    """Lazy-load CLIP model to avoid import overhead when not needed."""
    try:
        from transformers import CLIPProcessor, CLIPModel
        import torch
        model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
        processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
        device = "cuda" if torch.cuda.is_available() else "cpu"
        model = model.to(device)
        print(f"[CLIP] Loaded model on {device}")
        return model, processor, device
    except ImportError:
        print("[CLIP] transformers/torch not installed. Skipping CLIP classification.")
        return None, None, None


def clip_classify_image(image_url: str, model, processor, device,
                         labels=("a real photograph", "an AI-generated image")) -> tuple[bool, float]:
    """
    Download image and run CLIP zero-shot classification.
    Returns (is_ai, confidence).
    """
    import torch
    from PIL import Image

    try:
        resp = requests.get(image_url, timeout=10)
        image = Image.open(BytesIO(resp.content)).convert("RGB")
    except Exception as e:
        print(f"  [WARN] Could not fetch image {image_url}: {e}")
        return None, 0.0

    inputs = processor(
        text=list(labels),
        images=image,
        return_tensors="pt",
        padding=True
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs = outputs.logits_per_image.softmax(dim=1).cpu().numpy()[0]

    # probs[0] = P(real photo), probs[1] = P(AI-generated)
    is_ai = bool(probs[1] > 0.5)
    return is_ai, float(probs[1])


# ── Signal 3: EXIF/XMP Watermark Detection ───────────────────────────────────
def check_grok_watermark(image_url: str) -> tuple[bool | None, float]:
    """
    Check EXIF/XMP metadata for Grok watermark tags.
    Grok embeds 'Grok' in the Software or Artist EXIF field.
    """
    try:
        from PIL import Image
        from PIL.ExifTags import TAGS

        resp = requests.get(image_url, timeout=10)
        image = Image.open(BytesIO(resp.content))
        exif_data = image._getexif() or {}

        for tag_id, value in exif_data.items():
            tag = TAGS.get(tag_id, "")
            if isinstance(value, str) and "grok" in value.lower():
                return True, 1.0

        # Check XMP metadata (in raw bytes)
        raw = resp.content
        if b"Grok" in raw or b"xAI" in raw:
            return True, 0.90

        return None, 0.0
    except Exception:
        return None, 0.0


# ── Ensemble Classifier ───────────────────────────────────────────────────────
def classify_post(row: pd.Series, clip_model=None, processor=None, device=None) -> tuple[bool, float, str]:
    """
    Combine signals to produce final AI classification.
    Priority: Signal 3 (watermark) > Signal 1 (keywords) > Signal 2 (CLIP).
    Returns (is_ai, confidence, method_used).
    """
    # Signal 1: Keywords
    kw_result, kw_conf = keyword_classify(row.get("text", ""))
    if kw_result and kw_conf >= 0.95:
        return True, kw_conf, "keyword_high"

    # Signal 3: Watermark (if image URL available)
    media_urls = str(row.get("media_urls", ""))
    if media_urls:
        first_url = media_urls.split(",")[0].strip()
        if first_url.startswith("http"):
            wm_result, wm_conf = check_grok_watermark(first_url)
            if wm_result:
                return True, wm_conf, "exif_watermark"

            # Signal 2: CLIP
            if clip_model is not None:
                clip_result, clip_conf = clip_classify_image(first_url, clip_model, processor, device)
                if clip_result is not None:
                    # Ensemble: combine keyword (if any) + CLIP
                    if kw_result:
                        final_conf = 0.6 * clip_conf + 0.4 * kw_conf
                    else:
                        final_conf = clip_conf
                    return clip_result, final_conf, "clip+keyword"

    # Fallback: keyword only
    if kw_result is not None:
        return kw_result, kw_conf, "keyword_only"

    # Default: insufficient signal
    return False, 0.3, "no_signal"


def classify_dataframe(df: pd.DataFrame, use_clip: bool = False) -> pd.DataFrame:
    """Apply ensemble classifier to entire dataset."""
    df = df.copy()

    # Load CLIP if requested and available
    clip_model, processor, device = None, None, None
    if use_clip:
        clip_model, processor, device = load_clip_model()

    results = []
    for idx, row in df.iterrows():
        # Skip if already labeled (e.g., synthetic data)
        if pd.notna(row.get("ai_generated")) and row["ai_generated"] != "":
            results.append({
                "ai_generated": bool(row["ai_generated"]),
                "ai_confidence": 1.0,
                "detection_method": "pre_labeled"
            })
            continue

        is_ai, conf, method = classify_post(row, clip_model, processor, device)
        results.append({
            "ai_generated": is_ai,
            "ai_confidence": round(conf, 4),
            "detection_method": method
        })

        if idx % 100 == 0:
            print(f"  Classified {idx}/{len(df)} posts...")

    results_df = pd.DataFrame(results, index=df.index)
    df["ai_generated"]      = results_df["ai_generated"]
    df["ai_confidence"]     = results_df["ai_confidence"]
    df["detection_method"]  = results_df["detection_method"]

    return df


# ── Summary Statistics ────────────────────────────────────────────────────────
def print_detection_summary(df: pd.DataFrame):
    print("\n=== AI Detection Summary ===")
    print(f"Total posts:      {len(df)}")
    print(f"AI-generated:     {df['ai_generated'].sum()} ({df['ai_generated'].mean()*100:.1f}%)")
    print(f"\nDetection methods used:")
    print(df["detection_method"].value_counts().to_string())
    print(f"\nMean confidence by method:")
    print(df.groupby("detection_method")["ai_confidence"].mean().round(3).to_string())


# ── Main ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",     default="data/synthetic/synthetic_posts.csv")
    parser.add_argument("--output",    default="data/processed/classified_posts.csv")
    parser.add_argument("--use-clip",  action="store_true",
                        help="Enable CLIP image classifier (requires torch+transformers)")
    args = parser.parse_args()

    print(f"Loading data from {args.input}...")
    df = pd.read_csv(args.input)
    print(f"Loaded {len(df)} posts.")

    df = classify_dataframe(df, use_clip=args.use_clip)
    print_detection_summary(df)

    df.to_csv(args.output, index=False)
    print(f"\nSaved classified data → {args.output}")
